name: Deploy Melika app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set IMAGE names
        run: |
          SHORT_SHA=${GITHUB_SHA:0:7}
          REPO="${{ secrets.REGISTRY_URL }}/${{ secrets.REGISTRY_USER }}/melika"
          IMAGE_SHORT="$REPO:$SHORT_SHA"
          IMAGE_LATEST="$REPO:latest"
          echo "IMAGE_SHORT=$IMAGE_SHORT" >> $GITHUB_ENV
          echo "IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_SHORT }}
            ${{ env.IMAGE_LATEST }}

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PROJECT_PATH }}
            docker pull ${{ env.IMAGE_LATEST }}
            docker compose up -d
